version: '3.7'

services:
  web:
    build:
      context: .
    image: ricozl/webapp
    environment:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
